// Generated by CoffeeScript 1.6.3
define(['underscore'], function(_) {
  var CommanderRequestFragment;
  return CommanderRequestFragment = (function() {
    CommanderRequestFragment.prototype.m_requestParams = {};

    function CommanderRequestFragment() {
      this.m_requestParams = new Object();
    }

    CommanderRequestFragment.prototype.addParameter = function(name, value) {
      return this.doAddParameter(name, value);
    };

    CommanderRequestFragment.prototype.doAddParameter = function(name, value) {
      var arr, curValue;
      curValue = this.m_requestParams[name];
      if (curValue == null) {
        this.m_requestParams[name] = value;
        return;
      }
      if (!_.isArray(curValue)) {
        arr = new Array();
        arr.push(this.m_requestParams[name]);
        arr.push(value);
        this.m_requestParams[name] = arr;
        return;
      }
      this.m_requestParams[name].push(value);
      return null;
    };

    CommanderRequestFragment.prototype.doSetParameter = function(name, value) {
      return this.m_requestParams[name] = value;
    };

    CommanderRequestFragment.prototype.getMultiValuedParameter = function(name) {
      var result;
      result = this.m_requestParams[name];
      if (result == null) {
        return null;
      }
      if (!_.isArray(result)) {
        return [result];
      }
      return result;
    };

    CommanderRequestFragment.prototype.getParameter = function(name) {
      return this.m_requestParams[name];
    };

    CommanderRequestFragment.prototype.getParameters = function() {
      return this.m_requestParams;
    };

    CommanderRequestFragment.prototype.getRequestParams = function() {
      return this.m_requestParams;
    };

    CommanderRequestFragment.prototype.getStringParameter = function(name) {
      var result;
      result = this.m_requestParams[name];
      if (!_.isString(result)) {
        return null;
      }
      return result;
    };

    CommanderRequestFragment.prototype.setParameter = function(name, value) {
      if (value instanceof CommanderRequestFragment) {
        this.doSetParameter(name, value);
        return null;
      }
      if (value == null) {
        this.doSetParameter(name, '');
        return null;
      }
      if (_.isBoolean(value)) {
        this.doSetParameter(name, value != null ? value : {
          '1': '0'
        });
        return null;
      }
      if (value != null) {
        return this.doSetParameter(name, value.toString());
      }
    };

    return CommanderRequestFragment;

  })();
});

/*
//@ sourceMappingURL=CommanderRequestFragment.map
*/
