// Generated by CoffeeScript 1.6.3
define(function() {
  var ParsedString;
  return ParsedString = (function() {
    ParsedString.prototype.str = '';

    ParsedString.prototype.idx = 0;

    function ParsedString(s) {
      this.str = s;
      this.idx = 0;
    }

    ParsedString.prototype.check = function(c, complaint) {
      if (this.str.charAt(this.idx) !== c) {
        console.log(complaint + ' at ' + this.str.substring(this.idx));
      }
      return ++this.idx;
    };

    return ParsedString;

  })();
});

/*
//@ sourceMappingURL=ParsedString.map
*/
