// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var BetweenFilter;
  return BetweenFilter = (function(_super) {
    __extends(BetweenFilter, _super);

    function BetweenFilter(propertyName, operand1, operand2) {
      BetweenFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('between');
      this.setPropertyName(propertyName);
      this.setOperand1(operand1);
      this.setOperand2(operand2);
    }

    return BetweenFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=BetweenFilter.map
*/
