// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var GreaterOrEqualFilter;
  return GreaterOrEqualFilter = (function(_super) {
    __extends(GreaterOrEqualFilter, _super);

    function GreaterOrEqualFilter(propertyName, operand) {
      GreaterOrEqualFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('greaterOrEqual');
      this.setPropertyName(propertyName);
      this.setOperand1(operand);
    }

    return GreaterOrEqualFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=GreaterOrEqualFilter.map
*/
