// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var LessOrEqualFilter;
  return LessOrEqualFilter = (function(_super) {
    __extends(LessOrEqualFilter, _super);

    function LessOrEqualFilter(propertyName, operand) {
      LessOrEqualFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('lessOrEqual');
      this.setPropertyName(propertyName);
      this.setOperand1(operand);
    }

    return LessOrEqualFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=LessOrEqualFilter.map
*/
