// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var NotEqualFilter;
  return NotEqualFilter = (function(_super) {
    __extends(NotEqualFilter, _super);

    function NotEqualFilter(propertyName, operand) {
      NotEqualFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('notEqual');
      this.setPropertyName(propertyName);
      this.setOperand1(operand);
    }

    return NotEqualFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=NotEqualFilter.map
*/
