// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var NotFilter;
  return NotFilter = (function(_super) {
    __extends(NotFilter, _super);

    function NotFilter(filter) {
      NotFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('not');
      this.addFilter(filter);
    }

    return NotFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=NotFilter.map
*/
