// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var NotLikeFilter;
  return NotLikeFilter = (function(_super) {
    __extends(NotLikeFilter, _super);

    function NotLikeFilter(propertyName, operand) {
      NotLikeFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('notLike');
      this.setPropertyName(propertyName);
      this.setOperand1(operand);
    }

    return NotLikeFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=NotLikeFilter.map
*/
