// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

define(['../core/FindObjectsFilter'], function(FindObjectFilter) {
  var OrFilter;
  return OrFilter = (function(_super) {
    __extends(OrFilter, _super);

    function OrFilter() {
      var filters;
      filters = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      OrFilter.__super__.constructor.apply(this, arguments);
      this.setOperator('or');
      this.addFilter(filters);
    }

    return OrFilter;

  })(FindObjectFilter);
});

/*
//@ sourceMappingURL=OrFilter.map
*/
